# Generated by Django 3.2 on 2023-04-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_user_username'),
        ('reviews', '0004_auto_20230412_2350'),
    ]

    operations = [
    ]
