# Generated by Django 3.2 on 2023-04-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_20230414_1029'),
        ('reviews', '0007_alter_genres_name'),
    ]

    operations = [
    ]
